server:
    host: 0.0.0.0
    port: 8100
    publicPath: http://192.168.0.3:8100

iproxy:
    path: http://127.0.0.1:6878

stream:
    requestTimeout: 30
    clientIdleTimeout: 15

playlistFormat:
    useExtGrp: true
    useTvgNameAttr: true
    useGroupTitleAttr: true

playlistFetcher:
    acePlaylist:
        url: http://asplaylist.net/t/...
        interval: 60

logger:
    level: debug
